# Generated by Django 5.0.4 on 2024-04-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('idade', models.IntegerField()),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
