# Generated by Django 5.0.4 on 2024-04-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='email',
            field=models.EmailField(default='exemple@exemplo.com', max_length=254),
        ),
    ]
